[package]
name = "luna-backend"
version = "0.0.1"
edition = "2021"

[dependencies]
axum = {version = "0.7" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.37", features = ["full"] }