export enum PermissionKeys {
	ReadEvents = "read_events",
	AddEvents = "add_events",
	EditEvents = "edit_events",
	DeleteEvents = "delete_events",
	ReadCalendars = "read_calendars",
	AddCalendars = "add_calendars",
	EditCalendars = "edit_calendars",
	DeleteCalendars = "delete_calendars",
	ReadSources = "read_sources",
	AddSources = "add_sources",
	EditSources = "edit_sources",
	DeleteSources = "delete_sources",
	ManageInvites = "manage_invites",
	ManageUsers = "manage_users",
	ManageGlobalSettings = "manage_global_settings",
	ManageUserSettings = "manage_user_settings",
	ManageSessions = "manage_sessions",
	ManageResources = "manage_resources",
	Administrative = "administrative"
}