package queries

import (
	"luna-backend/errors"
	"luna-backend/types"
	"net/http"
	"time"

	"github.com/jackc/pgx/v5"
)

func (q *Queries) InsertSession(session *types.Session) *errors.ErrorTrace {
	// Session object does not have an ID or timestamp yet
	// These are generated by the database and updated in the session object

	query := `
		INSERT INTO sessions (userid, user_agent, is_api)
		VALUES ($1, $2, $3)
		RETURNING sessionid, created_at, last_seen;	
	`

	err := q.Tx.
		QueryRow(q.Context, query, session.User.UUID(), session.UserAgent, session.IsApi).
		Scan(&session.Id, &session.CreatedAt, &session.LastSeen)

	if err != nil {
		return errors.New().Status(http.StatusInternalServerError).
			AddErr(errors.LvlDebug, err).
			Append(errors.LvlWordy, "Could not insert session").
			Append(errors.LvlPlain, "Database error")
	}

	return nil
}

func (q *Queries) GetSessionAndUpdateLastSeen(userId types.ID, sessionId types.ID) (*types.Session, *errors.ErrorTrace) {
	query := `
		UPDATE sessions
		SET last_seen = NOW()
		WHERE userid = $1 AND sessionid = $2
		RETURNING *;
	`

	rows, err := q.Tx.Query(q.Context, query, userId, sessionId)
	if err != nil {
		return nil, errors.New().Status(http.StatusInternalServerError).
			AddErr(errors.LvlDebug, err).
			Append(errors.LvlDebug, "Could not execute query").
			Append(errors.LvlWordy, "Could not get or update session").
			Append(errors.LvlPlain, "Database error")
	}

	session, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[types.Session])
	switch err {
	case nil:
		break
	case pgx.ErrNoRows:
		return nil, errors.New().Status(http.StatusUnauthorized).
			Append(errors.LvlPlain, "Session expired")
	default:
		return nil, errors.New().Status(http.StatusInternalServerError).
			AddErr(errors.LvlDebug, err).
			Append(errors.LvlDebug, "Could not scan session").
			Append(errors.LvlWordy, "Could not get or update session").
			Append(errors.LvlPlain, "Database error")
	}

	return &session, nil
}

func (q *Queries) GetSessions(userId types.ID) ([]types.Session, *errors.ErrorTrace) {
	query := `
		SELECT *
		FROM sessions
		WHERE userid = $1;
	`

	rows, err := q.Tx.Query(q.Context, query, userId)
	if err != nil {
		return nil, errors.New().Status(http.StatusInternalServerError).
			AddErr(errors.LvlDebug, err).
			Append(errors.LvlDebug, "Could not execute query").
			Append(errors.LvlWordy, "Could not get sessions").
			Append(errors.LvlPlain, "Database error")
	}

	sessions, err := pgx.CollectRows(rows, pgx.RowToStructByName[types.Session])
	if err != nil {
		return nil, errors.New().Status(http.StatusInternalServerError).
			AddErr(errors.LvlDebug, err).
			Append(errors.LvlDebug, "Could not scan sessions").
			Append(errors.LvlWordy, "Could not get sessions").
			Append(errors.LvlPlain, "Database error")
	}

	return sessions, nil
}

func (q *Queries) DeleteSession(userId types.ID, sessionId types.ID) *errors.ErrorTrace {
	query := `
		DELETE FROM sessions
		WHERE userid = $1 AND sessionid = $2;
	`

	_, err := q.Tx.Exec(q.Context, query, userId, sessionId)
	if err != nil {
		return errors.New().Status(http.StatusInternalServerError).
			AddErr(errors.LvlDebug, err).
			Append(errors.LvlDebug, "Could not execute query").
			Append(errors.LvlWordy, "Could not delete session").
			Append(errors.LvlPlain, "Database error")
	}
	return nil
}

func (q *Queries) DeleteSessions(userid types.ID) *errors.ErrorTrace {
	query := `
		DELETE FROM sessions
		WHERE userid = $1;
	`

	_, err := q.Tx.Exec(q.Context, query, userid)
	if err != nil {
		return errors.New().Status(http.StatusInternalServerError).
			AddErr(errors.LvlDebug, err).
			Append(errors.LvlDebug, "Could not execute query").
			Append(errors.LvlWordy, "Could not delete sessions").
			Append(errors.LvlPlain, "Database error")
	}
	return nil
}

func (q *Queries) DeleteExpiredSessions(deleteBefore time.Time) *errors.ErrorTrace {
	query := `
		DELETE FROM sessions
		WHERE last_seen < $1;
	`

	_, err := q.Tx.Exec(q.Context, query, deleteBefore)
	if err != nil {
		return errors.New().Status(http.StatusInternalServerError).
			AddErr(errors.LvlDebug, err).
			Append(errors.LvlDebug, "Could not execute query").
			Append(errors.LvlWordy, "Could not delete expired sessions").
			Append(errors.LvlPlain, "Database error")
	}
	return nil
}
